remote_theme: "godalming123/minimal"   # fork with dark-mode support
plugins:
  - jekyll-remote-theme               # required by GitHub Pages


title: "ByteMastermind's Logs"
description: "AppSec Knowledge"

google_analytics: "G-5GN8JJ51EE"